### ISSUE TITLE
Customizing the schema

### ISSUE THREAD

**Issue by davidhyman** [touilleMan/marshmallow-mongoengine#14]
Hi there! Was looking forward to using your project -

Has something changed to break this behaviour? Following the docs: http://marshmallow-mongoengine.readthedocs.io/en/latest/tutorial.html#customizing-the-schema

`ma.fields.method` results in `AttributeError: module 'marshmallow_mongoengine.fields' has no attribute 'method'`

I can't see anything called `method` in `fields.py` or marshmallow itself. Was this functionality changed, or removed? Hoping for the former! :)
```
import marshmallow_mongoengine as ma
from core import models

class FruitSchema(ma.ModelSchema):
    class Meta:
        model = models.Fruit

    colour = ma.fields.method(serialize="_upper_case")

    def _upper_case(self, thing):
        return thing.colour.upper()
```
marshmallow==2.1.0
marshmallow-mongoengine==0.7.7

same behaviour on marshmallow==2.10.4

**Comment by lafrech** [comment]
I think it is a typo. Should be `Method` (capitalized).

**Comment by davidhyman** [comment]
smeg, now I see it in marshmallow.

Thaaaanks <3
