### ISSUE TITLE
Document the meta options available.

### ISSUE THREAD

**Issue by TheDodd** [touilleMan/marshmallow-mongoengine#4]
I really like this extension, it works great, but the meta options are not documented anywhere and [this code](https://github.com/touilleMan/marshmallow-mongoengine/blob/master/marshmallow_mongoengine/schema.py#L39) `self.model_skip_values = getattr(meta, 'model_skip_values', DEFAULT_SKIP_VALUES)` took a long time to diagnose. Namely the fact that `DEFAULT_SKIP_VALUES = (None, [], {})` was causing an important field to be filtered out of my API response, and I had to trace through the stack from the top of the marshmallow library down to this final piece.

Once again, works great, but documenting this behavior may save some other folks a great deal of time.

+1 for the awesome work so far!

**Comment by touilleMan** [comment]
Hi, I'm glad this project helped you :wink: 

Considering the lack of documentation, I've just added a tutorial, api documentation and configured the integration with readthedocs : http://marshmallow-mongoengine.readthedocs.org/en/latest/index.html

**Comment by paulocheque** [comment]
I think the default value for `DEFAULT_SKIP_VALUES` should be `[]`. I thought marshmallow had a bug.

**Comment by touilleMan** [comment]
I've documented `model_skip_values`, this should be more clearn now (see http://marshmallow-mongoengine.readthedocs.org/en/latest/apireference.html#marshmallow_mongoengine.SchemaOpts)

**Comment by TheDodd** [comment]
+1 thanks for doing that!
